name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

env:
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    name: RuboCop Linter
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "jruby"
          - "truffleruby"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
